### ISSUE TITLE
Bubleify eats buble error messages

### ISSUE THREAD

**Issue by josephg** [garthenweb/bubleify#4]
Using buble directly I get a nice error message telling me what I did wrong and how to fix it:

```
$ buble test.js 

---
1 : const yo = require('yo-yo');
2 : 
3 : document.body.appendChild(yo`<h1>Hi!</h1>`);
                              ^^^^^^^^^^^^^^^^
Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (3:26)
Error
    at TaggedTemplateExpression.initialise (/usr/local/lib/node_modules/buble/dist/buble.deps.js:7370:12)
    at /usr/local/lib/node_modules/buble/dist/buble.deps.js:5443:61
    at Array.forEach (native)
    ...
```

But with bubleify the message is gone:

```
$ browserify -t bubleify test.js
Error
    at TaggedTemplateExpression.initialise (/Users/josephg/src/es5/node_modules/bubleify/node_modules/buble/dist/buble.umd.js:2702:12)
    at /Users/josephg/src/es5/node_modules/bubleify/node_modules/buble/dist/buble.umd.js:855:61
    at Array.forEach (native)
    at CallExpression.initialise (/Users/josephg/src/es5/node_modules/bubleify/node_modules/buble/dist/buble.umd.js:855:12)
    ...
```

**Comment by garthenweb** [comment]
This is because Bublé throws a custom error message in case of a compiler error. Passing this error to browserify, it will only display the call stack (see [errorHandler](https://github.com/substack/node-browserify/blob/master/bin/cmd.js#L66)).

Providing both, the correct call stack and the message, is quite difficult and I did not found a proper solution. But I introduced a new option `bubleError`. With this its possible to decide on your own which one you prefer. It is available on v0.4.0.

Side note: This is just a problem with browserifies cli. When using browserifies JavaScript API you can define an error handler and parse the message on your own as you like it to be displayed!
